# Generated by Django 3.2.9 on 2021-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_image', models.ImageField(upload_to='media/')),
                ('post_price', models.PositiveIntegerField()),
                ('post_date', models.DateTimeField(verbose_name='投稿日時')),
            ],
        ),
    ]
