# Generated by Django 3.2.9 on 2022-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerowaste', '0003_usercreateform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreateForm',
        ),
    ]
